name: Build

on:
  workflow_call:
    inputs:
      go-version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ inputs.go-version }}
          cache: false

      - name: Install Dependencies
        run: go mod tidy

      - name: Compile
        run: go build -v ./...
  
